version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: pageviewservice
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - database_net
    deploy:
      replicas: 1
      
  rabbitmqsrv:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - rabbit_net
    deploy:
      replicas: 1

  pageviewservice:
    depends_on:
      - rabbitmqsrv
      - mysqldb
    image: d4jd-pageviewservice
    ports:
      - "8081:8081"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/pageviewservice?enabledTLSProtocols=TLSv1.2"
      SPRING_PROFILES_ACTIVE: 'mysql'
      SPRING_RABBITMQ_HOST: rabbitmqsrv
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rabbit_net
      - database_net
    deploy:
      replicas: 1

  springbootdocker:
    depends_on:
      - rabbitmqsrv
      - pageviewservice
    image: d4jd-springbootdocker
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_RABBITMQ_HOST: rabbitmqsrv
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rabbit_net
    deploy:
      replicas: 1

networks:
  rabbit_net:
    driver: overlay
  database_net:
    driver: overlay
